nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:3000'] # Allow requests from your frontend
        allow_headers: ['*'] # Allow all headers
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'] # Allow these HTTP methods
        max_age: 3600 # Cache preflight requests for 1 hour