<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250306025814 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE projects (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, required_skills JSON DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C93B3A477153098 ON projects (code)');
        $this->addSql('CREATE TABLE user_project_access (user_id INT NOT NULL, project_id INT NOT NULL, PRIMARY KEY(user_id, project_id))');
        $this->addSql('CREATE INDEX IDX_7A481F47A76ED395 ON user_project_access (user_id)');
        $this->addSql('CREATE INDEX IDX_7A481F47166D1F9C ON user_project_access (project_id)');
        $this->addSql('ALTER TABLE user_project_access ADD CONSTRAINT FK_7A481F47A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_project_access ADD CONSTRAINT FK_7A481F47166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD position VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD skills JSON DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_project_access DROP CONSTRAINT FK_7A481F47A76ED395');
        $this->addSql('ALTER TABLE user_project_access DROP CONSTRAINT FK_7A481F47166D1F9C');
        $this->addSql('DROP TABLE projects');
        $this->addSql('DROP TABLE user_project_access');
        $this->addSql('ALTER TABLE "user" DROP position');
        $this->addSql('ALTER TABLE "user" DROP skills');
    }
}
