<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250414223420 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE occupation_record (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, occupation_rate INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resource_id INT NOT NULL, project_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8254571989329D25 ON occupation_record (resource_id)');
        $this->addSql('CREATE INDEX IDX_82545719166D1F9C ON occupation_record (project_id)');
        $this->addSql('CREATE INDEX IDX_82545719896DBBDE ON occupation_record (updated_by_id)');
        $this->addSql('CREATE TABLE pole (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FD6042E1B03A8386 ON pole (created_by_id)');
        $this->addSql('CREATE TABLE resource (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, full_name VARCHAR(255) NOT NULL, skills JSON NOT NULL, occupation_rate DOUBLE PRECISION NOT NULL, availability_rate DOUBLE PRECISION NOT NULL, position VARCHAR(255) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, pole_id INT NOT NULL, project_manager_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BC91F416419C3385 ON resource (pole_id)');
        $this->addSql('CREATE INDEX IDX_BC91F41660984F51 ON resource (project_manager_id)');
        $this->addSql('CREATE TABLE resource_projects (resource_id INT NOT NULL, project_id INT NOT NULL, PRIMARY KEY(resource_id, project_id))');
        $this->addSql('CREATE INDEX IDX_F21F790989329D25 ON resource_projects (resource_id)');
        $this->addSql('CREATE INDEX IDX_F21F7909166D1F9C ON resource_projects (project_id)');
        $this->addSql('ALTER TABLE occupation_record ADD CONSTRAINT FK_8254571989329D25 FOREIGN KEY (resource_id) REFERENCES resource (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE occupation_record ADD CONSTRAINT FK_82545719166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE occupation_record ADD CONSTRAINT FK_82545719896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pole ADD CONSTRAINT FK_FD6042E1B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE resource ADD CONSTRAINT FK_BC91F416419C3385 FOREIGN KEY (pole_id) REFERENCES pole (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE resource ADD CONSTRAINT FK_BC91F41660984F51 FOREIGN KEY (project_manager_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE resource_projects ADD CONSTRAINT FK_F21F790989329D25 FOREIGN KEY (resource_id) REFERENCES resource (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE resource_projects ADD CONSTRAINT FK_F21F7909166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE occupation_record DROP CONSTRAINT FK_8254571989329D25');
        $this->addSql('ALTER TABLE occupation_record DROP CONSTRAINT FK_82545719166D1F9C');
        $this->addSql('ALTER TABLE occupation_record DROP CONSTRAINT FK_82545719896DBBDE');
        $this->addSql('ALTER TABLE pole DROP CONSTRAINT FK_FD6042E1B03A8386');
        $this->addSql('ALTER TABLE resource DROP CONSTRAINT FK_BC91F416419C3385');
        $this->addSql('ALTER TABLE resource DROP CONSTRAINT FK_BC91F41660984F51');
        $this->addSql('ALTER TABLE resource_projects DROP CONSTRAINT FK_F21F790989329D25');
        $this->addSql('ALTER TABLE resource_projects DROP CONSTRAINT FK_F21F7909166D1F9C');
        $this->addSql('DROP TABLE occupation_record');
        $this->addSql('DROP TABLE pole');
        $this->addSql('DROP TABLE resource');
        $this->addSql('DROP TABLE resource_projects');
    }
}
